repoURL: 'https://github.com/captain-arthur/app-of-apps.git'
apps:
# systemplatform project
# storage
# monitoring
# kafka

# longhorn
  - name: kube-prometheus-stack
    project: default
    namespace: monitoring
    source:
      path: kube-prometheus-stack
      customValues: true
      targetRevision: HEAD
      values:
        - ol-values.yaml